before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: main.go
    ldflags:
      - -s -w -X github.com/hashicorp/copywrite/cmd.version={{.Version}} -X github.com/hashicorp/copywrite/cmd.commit={{.ShortCommit}}
    binary: copywrite
archives:
  - replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'SHA256SUMS'
release:
  github:
    owner: hashicorp
    name: copywrite
  header: |
    - Attached to this release are compressed builds of the `copywrite` client

# Auto-publish to the HashiCorp homebrew tap: https://github.com/hashicorp/homebrew-tap
brews:
  - name: copywrite
    tap:
      owner: hashicorp
      name: homebrew-tap
      branch: copywrite
    commit_author:
      name: ${{ secrets.HOMEBREW_COMMIT_AUTHOR_NAME }}
      email: ${{ secrets.HOMEBREW_COMMIT_EMAIL }}
    homepage: 'https://github.com/hashicorp/copywrite'
    description: 'copywrite -- utilities for managing copyright headers and license files for GitHub repos'
    license: 'MPL-2.0'
    folder: Formula
    test: |
      system "#{bin}/copywrite --version"
