- id: add-headers
  name: Add copyright headers
  description: Adds missing copyright headers to all source code files
  entry: copywrite headers
  language: golang
  pass_filenames: false

- id: check-headers
  name: Validate copyright headers
  description: Checks if any copyright headers are missing, but does not make changes
  entry: copywrite headers --plan
  language: golang
  pass_filenames: false

- id: add-license
  name: Add or fix repo license
  description: Adds or updates a non-compliant LICENSE file
  entry: copywrite license
  language: golang
  pass_filenames: false

- id: check-license
  name: Validate repo license
  description: Checks if a LICENSE file is valid, but does not make changes
  entry: copywrite license --plan
  language: golang
  pass_filenames: false
